In [26]:
import pandas as pd
df = pd.read_csv('C:/Users/garap/Downloads/DATA ANALYSIS/robotaxi project/data/raw/SGO-2021-01_Incident_Reports_ADS.csv')

## selecting required columns

In [27]:
core_columns = [
    'Report ID',
    'Reporting Entity',
    'Report Submission Date',
    'Incident Date',
    'City',
    'State',
    'Roadway Type',
    'Crash With',
    'Highest Injury Severity Alleged',
    'SV Pre-Crash Movement',
    'SV Precrash Speed (MPH)',
    'Weather - Clear',
    'Weather - Rain',
    'Weather - Fog/Smoke/Haze',
    'Automation System Engaged?',
    'Engagement Status',
    'Within ODD?',
    'Narrative'
]

df_core = df[core_columns]

In [28]:
df_core.isnull().sum().sort_values(ascending=False)

City                               2
State                              2
Reporting Entity                   0
Report ID                          0
Incident Date                      0
Report Submission Date             0
Roadway Type                       0
Crash With                         0
Highest Injury Severity Alleged    0
SV Pre-Crash Movement              0
SV Precrash Speed (MPH)            0
Weather - Clear                    0
Weather - Rain                     0
Weather - Fog/Smoke/Haze           0
Automation System Engaged?         0
Engagement Status                  0
Within ODD?                        0
Narrative                          0
dtype: int64

In [29]:
df_core['Reporting Entity'].value_counts()

Reporting Entity
Waymo LLC                  726
Avride Inc.                 52
Zoox, Inc.                  42
Tesla, Inc.                 37
May Mobility                13
Motional                     8
Aurora Operations, Inc.      4
Beep, Inc.                   4
Nuro                         4
Hyundai Motor America        2
Ohmio, Inc.                  1
Stack AV                     1
Oxbotica                     1
Name: count, dtype: int64

In [30]:
df_core['Highest Injury Severity Alleged'].value_counts()

Highest Injury Severity Alleged
Property Damage. No Injured Reported    728
Minor W/O Hospitalization                63
No Injured Reported                      59
Minor W/ Hospitalization                 25
Unknown                                  14
Moderate W/ Hospitalization               4
Fatality                                  1
Moderate W/O Hospitalization              1
Name: count, dtype: int64

In [31]:
df_core['City'].value_counts().head(10)

City
San Francisco    240
Los Angeles      146
Austin           135
Phoenix           78
Dallas            35
Atlanta           33
Tempe             30
Las Vegas         20
Scottsdale        20
Santa Monica      15
Name: count, dtype: int64

In [32]:
weather_columns = [
    'Weather - Clear',
    'Weather - Rain',
    'Weather - Fog/Smoke/Haze'
]

df_core[weather_columns].sum()

Weather - Clear             YY YYYYYY Y  YYYYYYY YYYYYYYYYYYY Y YYY Y YYY ...
Weather - Rain                                                            ...
Weather - Fog/Smoke/Haze                                                  ...
dtype: object

In [33]:
df_clean = df_core.copy()
df_clean.head()

,Report ID,Reporting Entity,Report Submission Date,Incident Date,City,State,Roadway Type,Crash With,Highest Injury Severity Alleged,SV Pre-Crash Movement,SV Precrash Speed (MPH),Weather - Clear,Weather - Rain,Weather - Fog/Smoke/Haze,Automation System Engaged?,Engagement Status,Within ODD?,Narrative
0,30610-14656,"Zoox, Inc.",APR-2026,APR-2026,Las Vegas,NV,Street,Passenger Car,Property Damage. No Injured Reported,Proceeding Straight,21,Y,,,ADS,Verified Engaged,Yes,An unoccupied Zoox autonomous vehicle was trav...
1,31101-14654,Avride Inc.,APR-2026,MAR-2026,Austin,TX,Street,Animal,Property Damage. No Injured Reported,Unknown,15,Y,,,ADS,Verified Engaged,Yes,"On March [XXX], 2026 at 8:07 AM, an AVRIDE aut..."
2,31101-14653,Avride Inc.,APR-2026,MAR-2026,Dallas,TX,Street,Passenger Car,Property Damage. No Injured Reported,Proceeding Straight,24,,,,ADS,Verified Engaged,Yes,"On March [XXX], 2026 at 1:44 PM, an AVRIDE aut..."
3,31101-14652,Avride Inc.,APR-2026,MAR-2026,Dallas,TX,Intersection,"Other, see Narrative",No Injured Reported,Making Left Turn,13,Y,,,ADS,Verified Engaged,Yes,"On March [XXX], 2026, at 10:23 AM, an AVRIDE a..."
4,31101-14651,Avride Inc.,APR-2026,MAR-2026,Dallas,TX,Intersection,Passenger Car,Property Damage. No Injured Reported,Proceeding Straight,22,Y,,,ADS,Verified Engaged,Yes,"On March [XXX], 2026 at 10:12 PM, an AVRIDE au..."

## Finding Missing Values

In [34]:
missing_values = df_clean.isnull().sum().sort_values(ascending=False)

missing_values

City                               2
State                              2
Reporting Entity                   0
Report ID                          0
Incident Date                      0
Report Submission Date             0
Roadway Type                       0
Crash With                         0
Highest Injury Severity Alleged    0
SV Pre-Crash Movement              0
SV Precrash Speed (MPH)            0
Weather - Clear                    0
Weather - Rain                     0
Weather - Fog/Smoke/Haze           0
Automation System Engaged?         0
Engagement Status                  0
Within ODD?                        0
Narrative                          0
dtype: int64

In [35]:
missing_percentage = (
    df_clean.isnull().sum() / len(df_clean)
) * 100

missing_percentage.sort_values(ascending=False)

City                               0.223464
State                              0.223464
Reporting Entity                   0.000000
Report ID                          0.000000
Incident Date                      0.000000
Report Submission Date             0.000000
Roadway Type                       0.000000
Crash With                         0.000000
Highest Injury Severity Alleged    0.000000
SV Pre-Crash Movement              0.000000
SV Precrash Speed (MPH)            0.000000
Weather - Clear                    0.000000
Weather - Rain                     0.000000
Weather - Fog/Smoke/Haze           0.000000
Automation System Engaged?         0.000000
Engagement Status                  0.000000
Within ODD?                        0.000000
Narrative                          0.000000
dtype: float64

## Datetime Cleaning

In [36]:
df_clean[['Incident Date', 'Report Submission Date']].dtypes

Incident Date             object
Report Submission Date    object
dtype: object

In [37]:
df_clean['Incident Date'] = pd.to_datetime(
    df_clean['Incident Date'], format='%b-%Y'
)

df_clean['Report Submission Date'] = pd.to_datetime(
    df_clean['Report Submission Date'], format='%b-%Y'
)

In [38]:
df_clean[['Incident Date', 'Report Submission Date']].dtypes

Incident Date             datetime64[ns]
Report Submission Date    datetime64[ns]
dtype: object

## Feature Engineering

In [39]:
df_clean['Incident Year'] = (
    df_clean['Incident Date'].dt.year
)

df_clean['Incident Month'] = (
    df_clean['Incident Date'].dt.month
)

In [40]:
df_clean['Incident Month Name'] = (
    df_clean['Incident Date'].dt.month_name()
)

df_clean['Incident Quarter'] = (
    df_clean['Incident Date'].dt.quarter
)

In [41]:
df_clean['Reporting Delay Months'] = (
    (
        df_clean['Report Submission Date'].dt.year
        - df_clean['Incident Date'].dt.year
    ) * 12
    +
    (
        df_clean['Report Submission Date'].dt.month
        - df_clean['Incident Date'].dt.month
    )
)

In [42]:
df_clean[
    [
        'Incident Date',
        'Incident Year',
        'Incident Month',
        'Incident Month Name',
        'Incident Quarter',
        'Reporting Delay Months'
    ]
].head()

,Incident Date,Incident Year,Incident Month,Incident Month Name,Incident Quarter,Reporting Delay Months
0,2026-04-01,2026,4,April,2,0
1,2026-03-01,2026,3,March,1,1
2,2026-03-01,2026,3,March,1,1
3,2026-03-01,2026,3,March,1,1
4,2026-03-01,2026,3,March,1,1

In [43]:
df_clean['Incident Year'].value_counts().sort_index()

Incident Year
2025    599
2026    296
Name: count, dtype: int64

In [44]:
df_clean['Incident Month Name'].value_counts()

Incident Month Name
January      123
December     114
November     113
October      101
February      94
March         75
September     73
July          73
August        63
June          61
April          5
Name: count, dtype: int64

In [45]:
df_clean['Incident Quarter'].value_counts().sort_index()

Incident Quarter
1    292
2     66
3    209
4    328
Name: count, dtype: int64

In [46]:
df_clean['Reporting Delay Months'].value_counts().sort_index()

Reporting Delay Months
0    405
1    463
2     12
3      2
4      2
5      2
6      5
8      4
Name: count, dtype: int64

## Check for Duplicates

In [47]:
df_clean.duplicated().sum()

np.int64(1)

In [48]:
df_clean['Report ID'].duplicated().sum()

np.int64(34)

In [49]:
duplicate_ids = df_clean[
    df_clean['Report ID'].duplicated(keep=False)
]

duplicate_ids.sort_values('Report ID').to_csv('sorted_duplicates.csv', index=False)

## Categorical Profiling

In [50]:
df_clean['Reporting Entity'].value_counts()

Reporting Entity
Waymo LLC                  726
Avride Inc.                 52
Zoox, Inc.                  42
Tesla, Inc.                 37
May Mobility                13
Motional                     8
Aurora Operations, Inc.      4
Beep, Inc.                   4
Nuro                         4
Hyundai Motor America        2
Ohmio, Inc.                  1
Stack AV                     1
Oxbotica                     1
Name: count, dtype: int64

In [51]:
df_clean['Automation System Engaged?'].value_counts()

Automation System Engaged?
ADS     894
ADAS      1
Name: count, dtype: int64

In [52]:
df_clean['Engagement Status'].value_counts()

Engagement Status
Verified Engaged           867
Verified Not Engaged        26
Alleged Engaged              1
Unknown - see Narrative      1
Name: count, dtype: int64

In [53]:
df_clean['Within ODD?'].value_counts()

Within ODD?
Yes                                                          866
[REDACTED, MAY CONTAIN CONFIDENTIAL BUSINESS INFORMATION]     27
Exiting ODD                                                    1
No, see Narrative                                              1
Name: count, dtype: int64

In [54]:
df_clean['Crash With'].value_counts()

Crash With
Passenger Car                         282
SUV                                   207
Pickup Truck                           92
Heavy Truck                            86
Other, see Narrative                   69
Other Fixed Object                     52
Bus                                    35
Van                                    28
Motorcycle                             10
Animal                                  9
First Responder Vehicle                 8
Non-Motorist: Cyclist                   8
Pole / Tree                             4
Non-Motorist: Pedestrian                2
Non-Motorist: Scooter - Skateboard      2
Non-Motorist: Other                     1
Name: count, dtype: int64

In [55]:
df_clean['Roadway Type'].value_counts()

Roadway Type
Street               597
Intersection         213
Parking Lot           72
Highway / Freeway     13
Name: count, dtype: int64

### Cleaning weather columns

In [56]:
weather_cols = [
    'Weather - Clear',
    'Weather - Rain',
    'Weather - Fog/Smoke/Haze'
]

df_clean[weather_cols].eq('Y').sum(axis=1).value_counts()

1    718
0    177
Name: count, dtype: int64

In [57]:
def consolidate_weather(row):

    if row['Weather - Clear'] == 'Y':
        return 'Clear'

    elif row['Weather - Rain'] == 'Y':
        return 'Rain'

    elif row['Weather - Fog/Smoke/Haze'] == 'Y':
        return 'Fog/Smoke/Haze'

    else:
        return 'Unknown'

In [58]:
df_clean['Weather Condition'] = (
    df_clean.apply(consolidate_weather, axis=1)
)

In [59]:
df_clean['Weather Condition'].value_counts()

Weather Condition
Clear      680
Unknown    177
Rain        38
Name: count, dtype: int64

In [60]:
df_clean = df_clean.drop(columns=weather_cols)

#### taking a backup

In [61]:
df_analysis = df_clean.copy()

## Removing Duplicates

In [62]:
df_analysis = df_analysis.sort_values(
    'Report Submission Date'
)

In [63]:
df_analysis = df_analysis.drop_duplicates(
    subset='Report ID',
    keep='last'
)

In [64]:
original_rows = len(df_clean)

final_rows = len(df_analysis)

rows_removed = original_rows - final_rows

In [65]:
print("Original rows:", original_rows)
print("Final rows:", final_rows)
print("Rows removed:", rows_removed)

Original rows: 895
Final rows: 861
Rows removed: 34

In [66]:
cleaning_log = {
    "original_rows": original_rows,
    "duplicate_rows_removed": rows_removed,
    "deduplication_rule":
        "Latest submission retained per Report ID",
    "manual_review_ids": [
        "13781-11375",
        "31101-13612"
    ]
}

### Severity Normalization

In [67]:
df_analysis['Highest Injury Severity Alleged'].value_counts()

Highest Injury Severity Alleged
Property Damage. No Injured Reported    707
Minor W/O Hospitalization                60
No Injured Reported                      50
Minor W/ Hospitalization                 24
Unknown                                  14
Moderate W/ Hospitalization               4
Moderate W/O Hospitalization              1
Fatality                                  1
Name: count, dtype: int64

In [68]:
severity_map = {
    'Property Damage. No Injured Reported': 'No Injury',
    'No Injured Reported': 'No Injury',

    'Minor W/O Hospitalization': 'Minor Injury',
    'Minor W/ Hospitalization': 'Minor Injury',

    'Moderate W/O Hospitalization': 'Moderate Injury',
    'Moderate W/ Hospitalization': 'Moderate Injury',

    'Fatality': 'Fatality',

    'Unknown': 'Unknown'
}

df_analysis['Severity Group'] = (
    df['Highest Injury Severity Alleged']
    .map(severity_map)
)

df_analysis['Severity Group'].value_counts()

Severity Group
No Injury          757
Minor Injury        84
Unknown             14
Moderate Injury      5
Fatality             1
Name: count, dtype: int64

### Counterpart Normalization

In [69]:
df_analysis['Crash With'].value_counts()

Crash With
Passenger Car                         275
SUV                                   200
Pickup Truck                           88
Heavy Truck                            85
Other, see Narrative                   65
Other Fixed Object                     45
Bus                                    34
Van                                    28
Motorcycle                             10
Animal                                  8
First Responder Vehicle                 8
Non-Motorist: Cyclist                   7
Pole / Tree                             3
Non-Motorist: Scooter - Skateboard      2
Non-Motorist: Pedestrian                2
Non-Motorist: Other                     1
Name: count, dtype: int64

In [70]:
counterpart_map = {

    'Passenger Car': 'Passenger Vehicle',
    'SUV': 'Passenger Vehicle',
    'Pickup Truck': 'Passenger Vehicle',
    'Van': 'Passenger Vehicle',

    'Heavy Truck': 'Commercial Vehicle',
    'Bus': 'Commercial Vehicle',

    'Motorcycle': 'Two-Wheeler',

    'Non-Motorist: Cyclist': 'Vulnerable Road User',
    'Non-Motorist: Pedestrian': 'Vulnerable Road User',
    'Non-Motorist: Scooter - Skateboard': 'Vulnerable Road User',
    'Non-Motorist: Other': 'Vulnerable Road User',

    'Pole / Tree': 'Fixed Infrastructure',
    'Other Fixed Object': 'Fixed Infrastructure',

    'Animal': 'Animal',

    'First Responder Vehicle': 'Emergency Vehicle',

    'Other, see Narrative': 'Other / Unknown'
}

df_analysis['Crash Counterpart Group'] = (
    df['Crash With']
    .map(counterpart_map)
)

In [71]:
df_analysis.head()

,Report ID,Reporting Entity,Report Submission Date,Incident Date,City,State,Roadway Type,Crash With,Highest Injury Severity Alleged,SV Pre-Crash Movement,...,Within ODD?,Narrative,Incident Year,Incident Month,Incident Month Name,Incident Quarter,Reporting Delay Months,Weather Condition,Severity Group,Crash Counterpart Group
894,30270-11146,Waymo LLC,2025-06-01,2025-06-01,Austin,TX,Street,"Other, see Narrative",Property Damage. No Injured Reported,Proceeding Straight,...,Yes,"On June [XXX], 2025 at 1:28 PM CT a Waymo Auto...",2025,6,June,2,0,Unknown,No Injury,Other / Unknown
884,30270-11224,Waymo LLC,2025-06-01,2025-06-01,Mesa,AZ,Street,SUV,Property Damage. No Injured Reported,Proceeding Straight,...,Yes,"On June [XXX], 2025 at 5:34 PM MT a Waymo Auto...",2025,6,June,2,0,Clear,No Injury,Passenger Vehicle
885,30270-11218,Waymo LLC,2025-06-01,2025-06-01,San Francisco,CA,Intersection,Bus,Property Damage. No Injured Reported,Parked,...,Yes,"On June [XXX], 2025 at 6:48 PM PT a Waymo Auto...",2025,6,June,2,0,Unknown,No Injury,Commercial Vehicle
886,30270-11192,Waymo LLC,2025-06-01,2025-06-01,San Francisco,CA,Street,Passenger Car,Minor W/ Hospitalization,Stopped,...,Yes,"On June [XXX], 2025 at 2:27 PM PT a Waymo Auto...",2025,6,June,2,0,Clear,Minor Injury,Passenger Vehicle
887,30270-11204,Waymo LLC,2025-06-01,2025-06-01,Phoenix,AZ,Parking Lot,Van,No Injured Reported,Stopped,...,Yes,"On June [XXX], 2025 at 5:58 AM MT a Waymo Auto...",2025,6,June,2,0,Clear,No Injury,Passenger Vehicle

In [72]:
df_analysis.to_csv(
    'robotaxi_cleaned.csv',
    index=False
)